# Generated by Django 5.1 on 2024-08-28 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuralProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=14, verbose_name='CPF or CNPJ')),
                ('producer_name', models.CharField(max_length=128)),
                ('farm_name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agricultural_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vegetation_area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='core.ruralproducer')),
            ],
        ),
    ]
